name: CI

on: [ push ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@master
      - name: PHPUnit Tests
        uses: php-actions/phpunit@9
        with:
          bootstrap: src/bootstrap.php
