on:
  push:
    branches:
      - master

name: 🚀 Test and deploy to production

env:
  PHP_VERSION_REQUIRED: 8.2

jobs:
  phpstan:
    name: 🔧 Run PHPStan analysis
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 0
    steps:
      - name: 🚚 Download latest code
        uses: actions/checkout@v4

      - name: 🚚 Prepare PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION_REQUIRED }}
          extensions: mbstring, exif

      - name: 🚚 Install Composer development dependencies
        working-directory: ./
        run: composer install

      - name: 🚀 Run PHPStan analysis
        uses: php-actions/phpstan@v3
        with:
          php_version: ${{ env.PHP_VERSION_REQUIRED }}
          autoload_file: src/bootstrap.php
          configuration: phpstan.neon
          memory_limit: 512m
          php_extensions: mbstring exif

  phpunit:
    name: 🔧 Run unit tests
    needs: [ phpstan ]
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 0
    steps:
      - name: 🚚 Download latest code
        uses: actions/checkout@v4

      - name: 🚚 Prepare PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION_REQUIRED }}
          extensions: mbstring, exif

      - name: 🚚 Install Composer development dependencies
        working-directory: ./
        run: composer install

      - name: 🚀 Run PHPUnit tests (without requests)
        uses: php-actions/phpunit@v3
        with:
          php_version: ${{ env.PHP_VERSION_REQUIRED }}
          bootstrap: src/bootstrap.php
          configuration: phpunit.xml
          exclude_group: request
          php_extensions: mbstring exif

  web-deploy:
    name: 🎉 Deploy on production
    needs: [ phpunit ]
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - name: 🚚 Download latest code
        uses: actions/checkout@v3

      - name: 🚚 Prepare PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION_REQUIRED }}
          extensions: mbstring, exif

      - name: 🚚 Install Composer production dependencies
        working-directory: ./
        run: composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.ftp_server_dir }}
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            data/config.local.example.neon
            asset/
            asset/**
            temp/**
            tests/
            tests/**
            composer.json
            composer.lock
            readme.md
            web.config
            LICENSE
            README.md
            phpstan.neon
            phpstan-baseline.neon
            phpunit.xml
      - name: 🧹 Clean temp directory
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.ftp_server }}
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          workingDir: ${{ secrets.ftp_server_dir }}
          remoteDirectories: temp/latte;temp/nette-cache;temp/mini-curl;temp/staticmap;temp/temp-file
