on: [push]

name: 🚀 Deploy website on push
jobs:
  phpunit:
    name: 🔧 Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 8.0

      - name: 🚚 Install Composer Dependencies
        working-directory: ./
        run: composer install --dev --ignore-platform-req=php

      - name: PHPUnit tests (without requests)
        uses: php-actions/phpunit@v3
        with:
          php-version: 8.0
          bootstrap: src/bootstrap.php
          configuration: phpunit.xml
          exclude_group: request
