on: [ push ]

name: 🚀 Test and deploy website

jobs:
  phpunit:
    name: 🔧 Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Download latest code
        uses: actions/checkout@v3

      - name: 🚚 Prepare PHP
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 8.1
          extensions: mbstring, exif

      - name: 🚚 Install Composer development dependencies
        working-directory: ./
        run: composer install --dev

      - name: 🚀 Run PHPUnit tests (without requests)
        uses: php-actions/phpunit@v3
        with:
          php-version: 8.1
          bootstrap: src/bootstrap.php
          configuration: phpunit.xml
          exclude_group: request
          php_extensions: mbstring exif

  web-deploy:
    name: 🎉 Deploy on production webserver
    needs: [ phpunit ]
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Download latest code
        uses: actions/checkout@v3

      - name: 🚚 Prepare PHP
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: 8.1
          extensions: mbstring, exif

      - name: 🚚 Install Composer production dependencies
        working-directory: ./
        run: composer install --no-dev

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.ftp_server_dir }}
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            data/config.local.example.neon
            asset/
            asset/**
            temp/**
            tests/
            tests/**
            composer.json
            composer.lock
            readme.md
            web.config
            LICENSE
            README.md
            phpstan.neon
            phpstan-baseline.neon
            phpunit.xml
      - name: 🧹 Clean temp directory
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.ftp_server }}
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          workingDir: ${{ secrets.ftp_server_dir }}
          remoteDirectories: temp/latte;temp/nette-cache;temp/mini-curl;temp/staticmap;temp/temp-file
